### ISSUE TITLE
Create a component for creating Address 1s and Address 2s

### ISSUE THREAD

**Issue by benaduggan** [Tiny-Hands/tinyhands-client#154]
Currently we can only add addresses from VIFs and IRFs, so we need a angular component that can be used everywhere to create them. Since the addresses are so similar, it would be cool if we could make this one component, then we could pass in a type of address1 or address2 to the component  

### Tasks
- [ ] Create a component for creating addresses
    - [ ] Use modals triggered by a button to display the form
    - [ ] Use ng-transclude on the modal trigger button so it can be customized
    - [ ] Use the autocomplete directives for address1s and canonical names  (reference edit modal)
    - [ ] Use client side validation with error messages if entered incorrectly disabling the  submit button if invalid
- [ ] Add component to address 1 and address 2 pages
